BuildingManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('MySite.urls', namespace="site")),
    url(r'^admin/', admin.site.urls),
]

Manager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^view_bills/$', views.view_bills, name='viewBills'),
    url(r'^calculate_receipts/$', views.calculate_receipts, name='calculateReceipts'),
    url(r'^(?P<reserve_id>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.[0-9]*\W\d{2}:\d{2})/reject_reserve/$',
        views.reject_reserve,
        name='reject_reserve'),
    url(r'^(?P<reserve_id>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.[0-9]*\W\d{2}:\d{2})/accept_reserve/$',
        views.accept_reserve, name='accept_reserve'),
    url(r'^(?P<request_id>[0-9]+)/view_request/$', views.view_request, name='viewRequest'),
    url(r'^(?P<request_id>[0-9]+)/delete_request/$', views.delete_request, name='delete_request'),
    url(r'^select_contact/$', views.select_contact, name='select_contact'),
    url(r'^message/$', views.message, name='message'),
    url(r'^(?P<neighbour_id>[0-9]+)/edit_n/$', views.edit_n, name='editN'),
    url(r'^add_unit/$', views.add_unit, name='addUnit'),
    url(r'^add_request/$', views.add_request, name='addRequest'),
    url(r'^add_neighbour/$', views.add_neighbour, name='addNeighbour'),
    url(r'^requests/$', views.requests, name='requests'),
    url(r'^reserves_check/$', views.reserves_check, name='reservesCheck'),
    url(r'^paying_reports/$', views.paying_reports, name='payingReports'),
    url(r'^edit_unit/$', views.edit_unit, name='editUnit'),
    url(r'^edit_neighbours/$', views.edit_neighbours, name='editNeighbours'),
    url(r'^edit_complex_information/$', views.edit_complex_information, name='edit_complex_information'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^board/add_to_board$', views.add_to_board, name='add_to_board'),
    url(r'^board/$', views.view_board, name='board'),
    url(r'^events/$', views.view_event, name='events'),
    url(r'^enterBill/$', views.enter_bill, name='enterBill'),
    url(r'^(?P<unit_id>[0-9]+)/delete_unit/$', views.delete_unit, name='deleteUnit'),
    url(r'^(?P<neighbour_id>[0-9]+)/delete_neighbour/$', views.delete_neighbour, name='deleteNeighbour'),
    url(r'^$', views.account, name='account'),
    url(r'^add_facility/$', views.add_facility, name='addFacility'),
    url(r'^edit_facility/$', views.edit_facility, name='editFacility'),
    url(r'^(?P<facility_id>[0-9]+)/delete_facility/$', views.delete_facility, name='deleteFacility'),
    ]

MySite/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^resident/', include('Resident.urls', namespace="resident")),
    url(r'^manager/', include('Manager.urls', namespace="manager")),
    url(r'^$', views.index, name='index'),
    url(r'^send_feedback/$', views.send_feedback,name='send_feedback'),
    url(r'^logout/$', views.logout, name='log_out'),
    url(r'^forget_password/$', views.forget_password, name='forget_password'),
]

Manager/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models

from MyUser.models import Member

SUBJECT_CHOICES = (
    ('E', 'خطا در سامانه'),
    ('S', 'پیشنهاد امکانات جدید یا تغییر'),
    ('Q', 'سوال و راهنمایی'),
    ('C', 'شکایات'),
    ('O','سایر')
)

STATE_CHOICES = (
    ('W', 'در صف انتظار'),
    ('C', 'بررسی شده')
)


class Manager(models.Model):
    member = models.OneToOneField(Member)
    bank_account_num = models.IntegerField()

    def __str__(self):
        return str(self.member)

    # don't forget to write save


class Request(models.Model):
    manager = models.ForeignKey(Manager)
    title = models.CharField(max_length=20)
    subject = models.CharField(max_length= 1, choices=SUBJECT_CHOICES)
    text = models.TextField()
    state = models.CharField(max_length=2, choices=STATE_CHOICES)

MySite/models.py
# Create your models here.

from django.db import models

from Manager.models import Manager

FACILITY_TYPE = (
    ('P', 'استخر'),
    ('A', 'آمفی تئاتر'),
    ('G', 'سالن ورزش'),
    ('B', 'آلاچیق')
)

BILL_TYPE = (
    ('W', 'آب'),
    ('E', 'برق'),
    ('G', 'گاز'),
    ('P', 'تلفن')
)


class Unit(models.Model):
    area = models.IntegerField()
    block = models.ForeignKey('Block')

    def __str__(self):
        return str(self.block) + 'Unit : ' + str(self.id)


class Block(models.Model):
    complex = models.ForeignKey('Complex')

    def __str__(self):
        return 'complex: ' + str(self.complex.name) + ' block: ' + str(self.id)


class Bill(models.Model):
    type = models.CharField(max_length=1, choices=BILL_TYPE)
    num = models.IntegerField()
    cost = models.IntegerField()
    date = models.DateField()
    block = models.ForeignKey(Block)

    def str(self):
        return 'block' + str(self.block) + ' num: ' + str(self.num)


class Complex(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    manager = models.OneToOneField(Manager)
    unit_number = models.IntegerField()
    last_calculation_date = models.DateField()

    def __str__(self):
        return 'name: ' + self.name + ' manager: ' + str(self.manager)


class Facility(models.Model):
    type = models.CharField(max_length=20)
    block = models.ForeignKey('Block')
    cost = models.IntegerField()

    def __str__(self):
        return self.type


class Board(models.Model):
    block = models.OneToOneField(Block)

    def __str__(self):
        return str(self.block) + ' board: ' + str(self.id)


class News(models.Model):
    board = models.ForeignKey(Board)
    date = models.DateField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.board) + ' title: ' + str(self.title)


class Event(models.Model):
    board = models.ForeignKey(Board)
    date = models.DateField()
    cost = models.IntegerField()
    description = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.board) + ' description: ' + self.description

Manager/forms.py
import django
from django.forms import TextInput

from Manager.models import Manager, Request
from MyUser.models import Message
from MySite.models import Bill


class ManagerForm(django.forms.ModelForm):
    class Meta:
        model = Manager
        fields = '__all__'


class RequestForm(django.forms.ModelForm):
    class Meta:
        model = Request
        exclude = ['manager', 'state']


class MessageForm(django.forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['sender', 'theme_type']


class BillForm(django.forms.ModelForm):
    class Meta:
        model = Bill
        exclude = ['date']

Manager/views.py
import random
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db.models import Q, Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
# Create your views here.
from django.urls import reverse
from django.utils.datetime_safe import datetime

from Manager.forms import RequestForm, MessageForm, BillForm
from Manager.models import Request
from MySite.forms import EventForm, NewsForm, DisplayForm, ComplexForm
from MySite.models import Event, News, Unit, Block, Board
from MySite.models import Facility
from MyUser.forms import SignupForm1
from MyUser.forms import SignupForm2
from MyUser.models import Member, Message
from Resident.forms import ResidentForm
from Resident.models import Reserve, PayByBank, PayByAccount, Receipt
from Resident.models import Resident


@login_required
# the first page that manager see after login
def account(request):
    return render(request, 'manager/payingReports.html')


@login_required
# when manager click on the "add to board" in board page, a form to create event will be shown and manager can choose to
# create event or news, after clicking on "record" base on which manager chose an event or news will be created with
# date of today. then page will be redirected to board page to view all the event and news he created
def add_to_board(request):
    if request.method == 'POST':
        if request.POST['choose'] == 'event':
            form = EventForm(request.POST)
            if form.is_valid():
                event = form.save(commit=False)
                event.date = datetime.now().date()
                event.save()
        else:
            form = NewsForm(request.POST)
            if form.is_valid():
                news = form.save(commit=False)
                news.date = datetime.now().date()
                news.save()
        return HttpResponseRedirect(reverse('site:manager:board'))
    else:
        form = EventForm()
    return render(request, 'manager/add_to_board.html', {'form': form})


@login_required
# when manager click on "news" in the menu, he can see a table include of news of all block of that complex with theirs
# attributes
# can select a period to see news in that period
# can select an order of seeing news
def view_board(request):
    manager = request.user.member.manager
    events = None
    news_set = None
    if request.method == 'POST':
        form = DisplayForm(request.POST)
        if form.is_valid():
            news_set = News.objects.filter(board__block__complex=manager.complex,
                                           date__range=[form.cleaned_data['startDate'],
                                                        form.cleaned_data['finishDate']])
            events = Event.objects.filter(board__block__complex=manager.complex,
                                          date__range=[form.cleaned_data['startDate'], form.cleaned_data['finishDate']])
        else:
            news_set = News.objects.filter(board__block__complex=manager.complex)
            events = Event.objects.filter(board__block__complex=manager.complex)
        if request.POST['choose'] == 'جدیدترین':
            news_set = news_set.order_by('-date')
            events = events.order_by('-date')
        elif request.POST['choose'] == 'قدیمی ترین':
            news_set = news_set.order_by('date')
            events = events.order_by('date')
    else:
        news_set = News.objects.filter(board__block__complex=manager.complex)
        events = Event.objects.filter(board__block__complex=manager.complex)
    return render(request, 'manager/board.html', {'events': events, 'newsSet': news_set})


@login_required
# when manager click on "events" in the menu, he can see a table include of events of all block of that complex with
#  theirs attributes
# can select a period to see events in that period
# can select an order of seeing news
def view_event(request):
    manager = request.user.member.manager
    events = None
    if request.method == 'POST':
        form = DisplayForm(request.POST)
        if form.is_valid():
            events = Event.objects.filter(board__block__complex=manager.complex,
                                          date__range=[form.cleaned_data['startDate'], form.cleaned_data['finishDate']])
        else:
            events = Event.objects.filter(board__block__complex=manager.complex)
        if request.POST['choose'] == 'جدیدترین':
            events = events.order_by('-date')
    else:
        events = Event.objects.filter(board__block__complex=manager.complex)
    return render(request, 'manager/events.html', {'events': events})


@login_required
def edit_profile(request):
    """
    This function is for editting manager profile. With this section, manager can get his previeus profile and change them.
    :param request: Contain manager id for getting its information and Updating them.
    :return: After entering information, if there is not any fault in filling field, return to main page of manager site.
    """
    user = request.user
    user_form = SignupForm1(instance=user)
    if request.user.is_authenticated:
        if request.method == 'POST':
            user_form = SignupForm1(request.POST, instance=request.user)
            member = Member.objects.get(user=request.user)
            if user_form.is_valid():
                user_form.save()
                member.user = request.user
                member.phone_number = request.POST.get('phone_number')
                member.save()
                return HttpResponseRedirect(reverse('site:manager:account'))
    return render(request, 'manager/edit_profile.html', {'user': user, 'form': user_form})


@login_required
def edit_complex_information(request):
    """
    with this function manager can edit his complex information like name, address and number of blocks inside complex and also number of unit inside each block in complex.
    :param request: This passed field contain manager id and also complex id for getting its previuos informatoin. and also contains data filled by manager for editing previeus complex information
    :return: After filling required field, if there is no fault in entering data, opens main page of manager's site.
    """
    if request.method == 'POST':
        form = ComplexForm(request.POST, instance=request.user.member.manager.complex)
        blockNum = int(request.POST.get('blockNum'))
        if form.is_valid():
            complex = form.save(commit=False)
            complex.manager = Member.objects.filter(user=request.user)[0].manager
            complex.save()
            blocks = Block.objects.filter(complex=complex)
            s = len(blocks)
            if int(blockNum) < s:
                for i in range(s - blockNum):
                    blocks[i].delete()
            elif int(blockNum) > s:
                for i in range(int(blockNum) - s):
                    block = Block.objects.create(complex=complex)
                    board = Board.objects.create(block=block)
                    block.save()
                    board.save()
            return HttpResponseRedirect(reverse('site:manager:account'))
    else:
        form = ComplexForm(instance=request.user.member.manager.complex)
        blocks = Block.objects.filter(complex=form.instance)
        blockNum = len(blocks)
    return render(request, 'manager/edit_complex_information.html',
                  {'form': form.initial, 'blockNum': blockNum})


@login_required
def edit_neighbours(request):
    """
    With this function, manager can see neighbours for his complex.
    :param request: request contains manager id and complex id for getting resident that their complex is equal to this manager's complex.
    :return:As a result of this function, manager can see a html page with his complex's neighbours and their information like number of car, number of family member and their block number.
    """
    complex = request.user.member.manager.complex
    neighbours = Resident.objects.filter(unit__block__complex=complex)
    return render(request, 'manager/editNeighbours.html', {'neighbours': neighbours})


@login_required
def delete_neighbour(request,neighbour_id):
    """
    This function is for deleting special neighbour.
    :param request:
    :param neighbour_id: It is id of the neighbour, we want to delete it
    :return:This function result is deleting selected neighbour and returning and opening a page that shows all neighbours to managers
    """
    Resident.objects.get(id=neighbour_id).delete()
    return HttpResponseRedirect(reverse('site:manager:editNeighbours'))


@login_required
def edit_unit(request):
    '''
    This function is for getting all units belonging to this managers complex and thier data and showing them to the manager
    :param request: We can get manager id  and also complex id
    :return: As a result of this function, A page containing units and their informatoin is displayed.
    '''
    complex = request.user.member.manager.complex
    units = Unit.objects.filter(block__complex=complex)
    return render(request, 'manager/editUnit.html', {'units': units})


@login_required
# when manager click on "resident's paying reports" in the menu, he can see a table include of all paying reports of
#  all residents in all block of that complex with theirs attributes
# can select a period to see reports in that period
# can select an order of seeing reports
# can select a unit to see reports of that unit
def paying_reports(request):
        manager = request.user.member.manager
        bank_reports = None
        account_reports = None
        unit = None
        if request.method == 'POST':
            form = DisplayForm(request.POST)
            if form.is_valid():
                bank_reports = PayByBank.objects.filter(resident__unit__block__complex__manager=manager,

Manager/templates/manager/addFacility.html
{% extends 'manager/managerBase.html' %}

{% block title %}افزودن امکانات {% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}


{% block content %}
    <div class="main">
        <h5>افزودن امکانات</h5>
        <form action="" method="post" style="direction: ltr">{% csrf_token %}
            {% if error %}
                <div class="text-danger"> {{ error }} </div>
            {% endif %}
            <table class="tbl" border="0" align="center">
                <tbody>
                <tr>
                    <td><input type="text" name="name" id="name"></td>
                    <td><label for="name">نام</label></td>
                </tr>
                <tr>
                    <td><select name="block" id="block">
                        <option disabled selected style="color: black;">-----</option>
                        {% for block in blocks %}
                            <option value="{{ block.id }}">{{ block.id }}</option>
                        {% endfor %}
                    </select></td>
                    <td><label for="block">شماره بلوک </label></td>
                </tr>
                <tr>
                    <td><input type="number" name="cost" id="cost" min="1" max="10000"
                               title="هزینه را به تومان وارد کنید."></td>
                    <td><label for="cost">هزینه</label></td>
                </tr>
                </tbody>
            </table>
            <input type="submit" class="btn" value="ثبت"/>
        </form>


    </div>
{% endblock %}

Manager/templates/manager/addUnit.html
{% extends 'manager/managerBase.html' %}

{% block title %}اضافه کردن واحد{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}

{% block content %}
<div class="main">
    <h5>افزودن واحد جدید</h5>
    <form action="" method="post" style="direction: ltr">{% csrf_token %}
        {% if error %}
            <div class="text-danger"> {{ error }} </div>
        {% endif %}
        <table class="tbl" border="0" align="center">
            <tbody>
            <tr>
                <td><select name="block" id="block">
                    <option disabled selected style="color: black;">-----</option>
                    {% for block in blocks %}
                        <option value="{{ block.id }}">{{ block.id }}</option>
                    {% endfor %}
                </select></td>
                <td><label for="block">شماره بلوک </label></td>
            </tr>
            <tr>
                <td><input type="number" name="area" id="area" min="1" max="1000"></td>
                <td><label for="area">متراژ</label></td>
            </tr>
            </tbody>
        </table>
        <input type="submit" class="btn" value="ثبت"/>
    </form>


</div>
{% endblock %}

Manager/templates/manager/add_to_board.html
{% extends 'manager/managerBase.html' %}

{% block title %}اضافه کردن به بورد{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
    function f(){alert("درخواست با موفقیت ثبت شد."); window.location.href="editNeighbours.html";}
    function g(){
       var e = document.getElementById("from");
       var strUser = e.options[e.selectedIndex].value;
       var f = document.getElementById("cost_tag");
       if (strUser == "event")
    f.style.display='table-row';
       else
          f.style.display='none';
    }
{% endblock %}

{% block content %}
<div class="main">
    <h5>افزودن رویداد/خبر به برد</h5>
    <form action="" method="post" style="direction: rtl;">
        {% csrf_token %}
        <table class="tbl" border="0" align="center">
            <tbody>

            <tr>
                <td><label>نوع </label></td>
               <td>
                   <select name="choose" id="from" placeholder="" onchange="g()">
                    <option value="event">رویداد</option>
                    <option value="news">خبر</option>
                </select>
        </td>

            </tr>
            <tr>
                <td><label for="id_board">شماره بلوک</label></td>
                <td><input type="text" name="board" id="id_board"></td>

            </tr>

            <tr>
                <td><label for="id_title"> عنوان</label></td>

                <td><input type="text" name="title" id="id_title"></td>
            </tr>

            <tr>
                <td><label for="id_description">توضیحات </label></td>

                <td><input type="text" name="description" id="id_description"></td>
            </tr>

            <tr id="cost_tag"  >
                <td><label for="id_cost">مبلغ </label></td>

                <td><input type="text" name="cost" id="id_cost"></td>
            </tr>


            </tbody>
        </table>
        <input type="submit" class="btn" style="background-color:#F62A00 " value="ثبت">
    </form>

</div>
{% endblock %}

Manager/templates/manager/board.html
{% extends 'manager/managerBase.html' %}

{% block title %}اخبار{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
    function f(){alert("درخواست رزرو با موفقیت تایید گردید")}
    function g(){alert("درخواست رزرو با موفقیت رد گردید")}
    function printDiv(divName) {
    var printContents = document.getElementById(divName).innerHTML;
    var originalContents = document.body.innerHTML;

    document.body.innerHTML = printContents;

    window.print();

    document.body.innerHTML = originalContents;
    }
    function save(filename, divName) {
    var el = document.createElement('a');
    el.setAttribute('href', 'data:text/html;charset=utf-8,' +
    encodeURIComponent(document.getElementById(divName).innerHTML));
    el.setAttribute('download', filename);
    el.style.display = 'none';
    document.body.appendChild(el);
    el.click();
    document.body.removeChild(el);
    }
{% endblock %}

{% block content %}
<div class="main">
    <h5>بورد</h5>


    <form action="" method="post" style="direction:rtl;">
    {% csrf_token %}
        <select class="from" name="choose" placeholder="به ترتیب" style="width:100px;">
        <option value="قدیمی ترین">قدیمی ترین</option>
        <option value="جدیدترین">جدیدترین</option>
    </select>
    <label for="id_startDate">از تاریخ</label>
        <input type="date" name="startDate" id="id_startDate" class="from" style="width:200px;">
    <label for="id_finishDate">تا تاریخ</label>
        <input type="date" name="finishDate" id="id_finishDate" class="from" style="width:200px;">
    <input type="submit" class="btn"  value="نمایش">
</form>


    <div id="printableArea">
    <table>
        <tr>
            <th>توضیحات</th>
            <th>عنوان</th>
            <th>زمان و تاریخ</th>
            <th>شماره بلوک</th>
            <th>شماره</th>
            <th>ردیف</th>
        </tr>
        {% for news in newsSet %}
            <tr>
                <td>{{ news.description }}</td>
                <td>{{ news.title }}</td>
                <td>{{ news.date|date:"Y / m / d" }}</td>
                <td>{{ news.board.block_id }}</td>
                <td>{{ news.id }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}


    </table>
    </div>
    <a href="javascript:void(0)" onclick="printDiv('printableArea')" class="btn"><img
            src="../../static/images/printer.png" title="چاپ" class="linkImg1"></a>
    <a href="javascript:void(0)" onclick="save('reservesCheck.html', 'printableArea')" class="btn"><img
            src="../../static/images/save.png" title="ذخیره" class="linkImg2"></a>

</div>
{% endblock %}

Manager/templates/manager/editFacility.html
{% extends 'manager/managerBase.html' %}

{% block title %}ویرایش اطلاعات واحدها{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="../../../static/css/reqStyles.css"/>{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
    <div class="main" style="direction: ltr">
        <h5>امکانات مجتمع</h5>

        <table>
            <tr>
                <th>حذف</th>
                <th>هزینه رزرو</th>
                <th>شماره بلوک</th>
                <th>نام</th>
            </tr>
            {% for facility in facilities %}
                <tr>
                    <td><a href="{% url 'site:manager:deleteFacility' facility.id %}"
                           onclick="f({{ facility.id }})"><img
                            src="../../../static/images/delete.png" class="linkImg"></a></td>
                    <td>تومان{{ facility.cost }}</td>
                    <td>{{ facility.block.id }}</td>
                    <td>{{ facility.type }}</td>
                </tr>
            {% endfor %}
        </table>

        <a type="button" class="btn" href="{% url 'site:manager:addFacility' %}">اضافه کردن امکانات جدید</a>
        <a type="button" class="btn" href="{% url 'site:manager:edit_complex_information' %}">برگشت</a>

    </div>
{% endblock %}

Manager/templates/manager/managerBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <style>
         @font-face {
             font-family: 'brandon';
             src: url("{% static "fonts/BRoya.ttf"%}") format('truetype');
             font-style: normal;
             font-weight: normal;
         }
         body{
             margin: 0;
         }
        .container{
            margin: 0;
            padding:0;
            width:100%;
        }
        #footer {
            font-family: brandon;
            text-align: center;
            width: 100%;
            position: absolute;
            height: 150px;
            background-color: #00293E;
            color: white;
            margin-top: 50px;
        }

        .foot{
           font-size: 16px;
        }
         .text-danger{
             color: red;
             direction: rtl;

         }

         input, select {
             width: 250px;
             height: 35px;
             border-radius: 3px;
             font-family: brandon;
             font-size: 18px;
             text-align: right;
         }

         #id_text {
            font-family: brandon;
            font-size: 18px;
            text-align: right;
             width: 400px;
             height: 150px;
         }

         .address{
         width: 250px;
         position: absolute;
         top: 6%;
         right: 2%;
         font-size: 18px;
         font-family: brandon;
         color: white;
         text-align: right;
         }

         .logo{
         position: absolute;
         top: 20%;
         left: 5%;
         max-width: 100px;
         }

         .highlighted {
             background-color: rgba(0, 0, 0, .4);
             text-align: center;
         }


    </style>
    {% block css %}{% endblock %}

    <script type="text/javascript">{% block script %}{% endblock %}</script>
</head>
<body>
<div class="container">

    <img class="cover" src="../../../static/images/test.jpg">
    <div class="topright"><img class="img-circle" src="../../../static/images/user_profile_female.jpg">
        <p class="highlighted"> {{ user.get_full_name }}</p></div>
    <div class="topleft" style="display:grid; z-index:5">
        <a href="{% url 'site:manager:select_contact'%}"><img src="../../../static/images/message.png"
                                                              style="height:50px;width:50px;"/></a>
        <a href="/logout/">خروج</a>
        <p>96/5/5</p>

    </div>

</div>

</div>
<div class="menu">
    <ul>
        <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">ویرایش اطلاعات</a>
            <div class="dropdown-content">
                <a href="{% url 'site:manager:edit_profile'%}">اطلاعات حساب</a>
                <a href="{% url 'site:manager:edit_complex_information'%}">اطلاعات مجتمع</a>
                <a href="{% url 'site:manager:editNeighbours'%}">اطلاعات ساکنین</a>
                <a href="{% url 'site:manager:editUnit'%}">اطلاعات واحدها</a>
            </div>
        </li>
        <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">بورد</a>
            <div class="dropdown-content">
                <a href="{% url 'site:manager:board' %}">اخبار</a>
                <a href="{% url 'site:manager:events' %}">رویدادها</a>
                <a href="{% url 'site:manager:add_to_board' %}">اطلاعیه جدید</a>
            </div>
        </li>
        <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">گزارشات</a>
            <div class="dropdown-content">
                <a href="{% url 'site:manager:payingReports'%}">پرداخت های همسایه ها</a>
            </div>
        </li>
        <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">رزرو</a>
            <div class="dropdown-content">
                <a href="{% url 'site:manager:reservesCheck'%}">درخواست های رزرو</a>
            </div>
        </li>

        <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">امور مالی</a>
            <div class="dropdown-content">
                <a href="{% url 'site:manager:enterBill'%}">وارد کردن قبض</a>
                <a href="{% url 'site:manager:viewBills' %}">محاسبه ی شارژ</a>
            </div>
        </li>


        <a href="{% url 'site:manager:requests'%}" class="notDropdown">درخواست پشتیبانی</a>

    </ul>
</div>

{% block content %}
{% endblock %}
<div id="footer">
    <div class="address">
        <p>نشانی: تهران، خیابان آزادی، دانشگاه شریف، دانشکده مهندسی کامپیوتر</p>
        <p>تلفن تماس: 02166161234</p>
    </div>

    <p class="footer-block">طراحی و اجرا: شرکت نرم افزاری آسا</p>
    <p class="foot">کلیه حقوق محفوظ و متعلق به آسا می باشد</p>
    <div ><img class="logo" src="../../../static/images/LOGO.png"></div>
</div>
</body>
</html>

Manager/templates/manager/viewRequest.html
{% extends 'manager/managerBase.html' %}

{% block title %}مشاهده درخواست{% endblock %}
{% load static %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/viewBillStyles.css' %}"/>{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
<div class="main">
    <h5>درخواست شماره{{ request.id }}</h5>

    <h4>عنوان: {{ request.title }}</h4>
    <h4>موضوع: {{ request.get_subject_display }}</h4>

    <p style="text-align: right" >
{{ request.text }}
    </p>

    <a href="javascript:void(0)" class="btn"><img src="{% static 'images/printer.png' %}" class="linkImg1"></a>
    <a href="javascript:void(0)" class="btn"><img src="{% static 'images/save.png' %}" class="linkImg2"></a>

</div>
{% endblock %}