BuildingManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('MySite.urls', namespace="site")),
    url(r'^admin/', admin.site.urls),
]

MySite/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^resident/', include('Resident.urls', namespace="resident")),
    url(r'^manager/', include('Manager.urls', namespace="manager")),
    url(r'^$', views.index, name='index'),
    url(r'^send_feedback/$', views.send_feedback,name='send_feedback'),
    url(r'^logout/$', views.logout, name='log_out'),
    url(r'^forget_password/$', views.forget_password, name='forget_password'),
]

Resident/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^select_contact/$', views.select_contact, name='select_contact'),
    url(r'^message/$', views.message, name='message'),
    url(r'^reserves/$', views.view_reserves, name='myReserves'),
    url(r'^reserve/$', views.reserve, name='reserve'),
    url(r'^(?P<receipt_id>[0-9]+)/select_payWay/$', views.select_pay_way, name='select_payWay'),
    url(r'^(?P<receipt_id>[0-9]+)/view_bill/$', views.view_bill, name='viewBill'),
    url(r'^bills/$', views.view_bills, name='bills'),
    url(r'^paying_reports/$', views.paying_reports, name='payingReports_user'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^board/$', views.view_board, name='board'),
    url(r'^events/$', views.view_event, name='events'),
    url(r'^increase/$', views.increase_cash, name='increase'),
    url(r'^$', views.account, name='account'),
    ]

MySite/models.py
# Create your models here.

from django.db import models

from Manager.models import Manager

FACILITY_TYPE = (
    ('P', 'استخر'),
    ('A', 'آمفی تئاتر'),
    ('G', 'سالن ورزش'),
    ('B', 'آلاچیق')
)

BILL_TYPE = (
    ('W', 'آب'),
    ('E', 'برق'),
    ('G', 'گاز'),
    ('P', 'تلفن')
)


class Unit(models.Model):
    area = models.IntegerField()
    block = models.ForeignKey('Block')

    def __str__(self):
        return str(self.block) + 'Unit : ' + str(self.id)


class Block(models.Model):
    complex = models.ForeignKey('Complex')

    def __str__(self):
        return 'complex: ' + str(self.complex.name) + ' block: ' + str(self.id)


class Bill(models.Model):
    type = models.CharField(max_length=1, choices=BILL_TYPE)
    num = models.IntegerField()
    cost = models.IntegerField()
    date = models.DateField()
    block = models.ForeignKey(Block)

    def str(self):
        return 'block' + str(self.block) + ' num: ' + str(self.num)


class Complex(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    manager = models.OneToOneField(Manager)
    unit_number = models.IntegerField()
    last_calculation_date = models.DateField()

    def __str__(self):
        return 'name: ' + self.name + ' manager: ' + str(self.manager)


class Facility(models.Model):
    type = models.CharField(max_length=20)
    block = models.ForeignKey('Block')
    cost = models.IntegerField()

    def __str__(self):
        return self.type


class Board(models.Model):
    block = models.OneToOneField(Block)

    def __str__(self):
        return str(self.block) + ' board: ' + str(self.id)


class News(models.Model):
    board = models.ForeignKey(Board)
    date = models.DateField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.board) + ' title: ' + str(self.title)


class Event(models.Model):
    board = models.ForeignKey(Board)
    date = models.DateField()
    cost = models.IntegerField()
    description = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.board) + ' description: ' + self.description

MyUser/models.py
from django.contrib.auth.models import User
from django.db import models


MESSAGE_THEME_TYPE = (
    (0, 'بدون قالب'),
    (1, 'قالب 1'),
    (2, 'قالب 2'),
)


class Member(models.Model):
    user = models.OneToOneField(User)
    phone_number = models.CharField(max_length=12)
    image = models.FileField(upload_to='static/images/profile_picture',
                             default='../static/images/user_profile_female.jpg')

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Message(models.Model):
    text = models.TextField(max_length=1000)
    theme_type = models.IntegerField(choices=MESSAGE_THEME_TYPE)
    sender = models.ForeignKey(Member, related_name='sender')
    receiver = models.ForeignKey(Member, related_name='receiver')

    def __str__(self):
        return 'sender: ' + str(self.sender) + ' receiver: ' + str(self.receiver)

Resident/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from MySite.models import Facility, Unit
from MyUser.models import Member

RESERVE_STATE = {
    ('NC', 'بررسی نشده'),
    ('R', 'رد شده'),
    ('A', 'تایید شده')
}

RECEIPT_STATE = {
    ('P', 'پرداخت شده'),
    ('NP', 'پرداخت نشده')
}


class Resident(models.Model):
    member = models.OneToOneField(Member)
    member_count = models.IntegerField()
    car_count = models.IntegerField()
    unit = models.OneToOneField(Unit)

    def __str__(self):
        return str(self.member)


class Reserve(models.Model):
    reserve_date = models.DateTimeField(primary_key=True)
    use_finishDate = models.DateTimeField()
    use_startDate = models.DateTimeField()
    cost = models.IntegerField()
    state = models.CharField(max_length=2, choices=RESERVE_STATE)
    resident = models.ForeignKey(Resident)
    facility = models.ForeignKey(Facility)

    def __str__(self):
        return 'resident: ' + str(self.resident) + ' facility: ' + str(self.facility) + ' reserve date:' + \
               str(self.reserve_date)


class Receipt(models.Model):
    start_date = models.DateField()
    finish_date = models.DateField()
    cost = models.IntegerField(null=True)
    state = models.CharField(max_length=2, choices=RECEIPT_STATE)
    resident = models.ForeignKey(Resident)

    def __str__(self):
        return 'date: ' + str(self.start_date) + ' cost: ' + str(self.cost)


class Account(models.Model):
    cash = models.PositiveIntegerField()
    resident = models.OneToOneField(Resident)

    def __str__(self):
        return 'resident: ' + str(self.resident)


class PayByBank(models.Model):
    date = models.DateField(primary_key=True)
    amount = models.IntegerField()
    resident = models.OneToOneField(Resident)
    receipt = models.OneToOneField(Receipt)

    def __str__(self):
        return 'resident: ' + str(self.resident) + ' date: ' + str(self.date)


class PayByAccount(models.Model):
    date = models.DateField(primary_key=True)
    amount = models.IntegerField()
    account = models.OneToOneField(Account)
    receipt = models.OneToOneField(Receipt)

    def __str__(self):
        return str(self.account) + ' date: ' + str(self.date)

Resident/forms.py
import django
from django import forms
from django.contrib.auth.models import User

from MyUser.models import Message
from Resident.models import Resident, Reserve, Account


class Resident_UserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['username','email']


class ResidentForm(django.forms.ModelForm):
    class Meta:
        model = Resident
        fields = ['member_count', 'car_count', 'unit']


class ReserveForm(django.forms.ModelForm):
    class Meta:
        model = Reserve
        fields = ['facility']

class DateForm(django.forms.Form):
    use_startDate_0 = forms.DateField()
    use_startDate_1 = forms.TimeField()
    use_finishDate_0 = forms.DateField()
    use_finishDate_1 = forms.TimeField()


class MessageForm(django.forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['sender', 'theme_type']


class AcountForm(django.forms.ModelForm):
    class Meta:
        model = Account
        exclude = ['resident']

Resident/templates/resident/account.html
{% extends 'resident/residentBase.html' %}

{% block title %}حساب کاربری - ساکن{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
{% endblock %}

Resident/templates/resident/board.html
{% extends 'resident/residentBase.html' %}

{% block title %}اخبار{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
    function f(){alert("درخواست رزرو با موفقیت تایید گردید")}
    function g(){alert("درخواست رزرو با موفقیت رد گردید")}
    function printDiv(divName) {
    var printContents = document.getElementById(divName).innerHTML;
    var originalContents = document.body.innerHTML;

    document.body.innerHTML = printContents;

    window.print();

    document.body.innerHTML = originalContents;
    }
    function save(filename, divName) {
    var el = document.createElement('a');
    el.setAttribute('href', 'data:text/html;charset=utf-8,' +
    encodeURIComponent(document.getElementById(divName).innerHTML));
    el.setAttribute('download', filename);
    el.style.display = 'none';
    document.body.appendChild(el);
    el.click();
    document.body.removeChild(el);
    }
{% endblock %}

{% block content %}

<div class="main">
    <h5>اخبار</h5>


    <form action="" method="post" style="direction:rtl;">
    {% csrf_token %}
        <select class="from" name="choose" placeholder="به ترتیب" style="width:100px;">
        <option value="قدیمی ترین">قدیمی ترین</option>
        <option value="جدیدترین">جدیدترین</option>
    </select>
    <label for="id_startDate">از تاریخ</label>
        <input type="date" name="startDate" id="id_startDate" class="from" style="width:200px;">
    <label for="id_finishDate">تا تاریخ</label>
        <input type="date" name="finishDate" id="id_finishDate" class="from" style="width:200px;">
    <input type="submit" class="btn"  value="نمایش">
</form>


    <div id="printableArea">
    <table>
        <tr>
            <th>توضیحات</th>
            <th>عنوان</th>
            <th>زمان و تاریخ</th>
            <th>شماره</th>
            <th>ردیف</th>
        </tr>
        {% for news in newsSet %}
            <tr>
                <td>{{ news.description }}</td>
                <td>{{ news.title }}</td>
                <td>{{ news.date|date:"Y / m / d" }}</td>
                <td>{{ news.id }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}


    </table>
    </div>

    <a href="javascript:void(0)" onclick="printDiv('printableArea')" class="btn"><img
            src="../../static/images/printer.png" title="چاپ" class="linkImg1"></a>
    <a href="javascript:void(0)" onclick="save('reservesCheck.html', 'printableArea')" class="btn"><img
            src="../../static/images/save.png" title="ذخیره" class="linkImg2"></a>

</div>

{% endblock %}

Resident/templates/resident/events.html
{% extends 'resident/residentBase.html' %}

{% block title %}رویدادها{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
    function f(){alert("درخواست رزرو با موفقیت تایید گردید")}
    function g(){alert("درخواست رزرو با موفقیت رد گردید")}
    function printDiv(divName) {
    var printContents = document.getElementById(divName).innerHTML;
    var originalContents = document.body.innerHTML;

    document.body.innerHTML = printContents;

    window.print();

    document.body.innerHTML = originalContents;
    }
    function save(filename, divName) {
    var el = document.createElement('a');
    el.setAttribute('href', 'data:text/html;charset=utf-8,' +
    encodeURIComponent(document.getElementById(divName).innerHTML));
    el.setAttribute('download', filename);
    el.style.display = 'none';
    document.body.appendChild(el);
    el.click();
    document.body.removeChild(el);
    }
{% endblock %}

{% block content %}
    <div class="main">
        <h5>رویدادها</h5>


        <form action="" method="post" style="direction:rtl;">
            {% csrf_token %}
            <select class="from" name="choose" placeholder="به ترتیب" style="width:100px;">
                <option value="قدیمی ترین">قدیمی ترین</option>
                <option value="جدیدترین">جدیدترین</option>
            </select>
            <label for="id_startDate">از تاریخ</label>
            <input type="date" name="startDate" id="id_startDate" class="from" style="width:200px;">
            <label for="id_finishDate">تا تاریخ</label>
            <input type="date" name="finishDate" id="id_finishDate" class="from" style="width:200px;">
            <input type="submit" class="btn" value="نمایش">
        </form>

        <div id="printableArea">
            <table>
                <tr>
                    <th>مبلغ</th>
                    <th>توضیحات</th>
                    <th>زمان و تاریخ</th>
                    <th>شماره بلوک</th>
                    <th>شماره</th>
                    <th>ردیف</th>
                </tr>
                {% for event in events %}
                    <tr>
                        <td>{{ event.cost }}</td>
                        <td>{{ event.description }}</td>
                        <td>{{ event.date|date:"Y / m / d" }}</td>
                        <td>{{ event.board.block_id }}</td>
                        <td>{{ event.id }}</td>
                        <td>
                            {{ forloop.counter }}
                        </td>
                    </tr>
                {% endfor %}


            </table>
        </div>

        <a href="javascript:void(0)" onclick="printDiv('printableArea')" class="btn"><img
                src="../../static/images/printer.png" title="چاپ" class="linkImg1"></a>
        <a href="javascript:void(0)" onclick="save('reservesCheck.html', 'printableArea')" class="btn"><img
                src="../../static/images/save.png" title="ذخیره" class="linkImg2"></a>

    </div>
{% endblock %}

Resident/templates/resident/increase.html
{% extends 'resident/residentBase.html' %}

{% block title %}افزايش اعتبار{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../../static/css/addReqStyle.css"/>{% endblock %}

{% block script %}
{% endblock %}

{% block content %}

    <div class="main">
        <h5>افزايش اعتبار</h5>
        <p style="color: #1E656D; font-weight: bold;">موجودي فعلي شما: {{acount.cash}} ريال </p>
        <p>لطفا مبلغ مورد نظر خود را جهت افزايش اعتبار وارد فرماييد</p>
        <form action="" method="post">
            {% csrf_token %}
            <table class="tbl" border="0" align="center">
                <tbody>

                <tr style="">
                    <td><label for="cash">ريال</label></td>
                    <td>{{form.cash}}</td>
                </tr>


                </tbody>
            </table>
          <img src="../../../static/images/BankTejarat.png" style="float:left; padding-bottom: 100px;">
            <input type="submit" class="btn" value="پرداخت از طريق بانک تجارت" style="width: 250px; font-size:18px; font-weight: bold; margin-bottom: 100px;">
        </form>


    </div>

{% endblock %}

Resident/templates/resident/myReserves.html
{% extends 'resident/residentBase.html' %}

{% block title %}رزروهای من{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
function f(){alert("درخواست رزرو با موفقیت تایید گردید")}
    function g(){alert("درخواست رزرو با موفقیت رد گردید")}
    function printDiv(divName) {
    var printContents = document.getElementById(divName).innerHTML;
    var originalContents = document.body.innerHTML;

    document.body.innerHTML = printContents;

    window.print();

    document.body.innerHTML = originalContents;
    }
    function save(filename, divName) {
    var el = document.createElement('a');
    el.setAttribute('href', 'data:text/html;charset=utf-8,' +
    encodeURIComponent(document.getElementById(divName).innerHTML));
    el.setAttribute('download', filename);
    el.style.display = 'none';
    document.body.appendChild(el);
    el.click();
    document.body.removeChild(el);
    }
{% endblock %}

{% block content %}

<div class="main">
    <h5>درخواست های رزرو من</h5>

    <form action="" method="post" style="direction: rtl;">
    {% csrf_token %}
        <select class="from" name="choose" placeholder="به ترتیب" style="width:100px;">
        <option value="قدیمی ترین">قدیمی ترین</option>
        <option value="جدیدترین">جدیدترین</option>
    </select>
    <label for="id_startDate">از تاریخ</label>
        <input type="date" name="startDate" id="id_startDate" class="from" style="width:200px;">
    <label for="id_finishDate">تا تاریخ</label>
        <input type="date" name="finishDate" id="id_finishDate" class="from" style="width:200px;">
    <input type="submit" class="btn"  value="نمایش">
</form>

    <div id="printableArea">
    <table>
        <tr>

            <th style="width: 10%">مبلغ به ریال </th>
            <th style="width: 10%">وضعیت</th>
            <th style="width: 15%">زمان و تاریخ ایجاد</th>
            <th style="width: 15%">زمان و تاریخ پایان استفاده</th>
            <th style="width: 15%">زمان و تاریخ شروع استفاده</th>
            <th style="width: 10%">امکان</th>
            <th style="width: 10%">ردیف</th>
        </tr>


        {% for reserve in reserves %}
            <tr>
                <td>{{ reserve.cost }}</td>
                <td>{{ reserve.get_state_display }}</td>
                <td>{{ reserve.reserve_date|date:"Y / m / d" }}</td>
                <td>{{ reserve.use_finishDate|date:"Y / m / d" }}</td>
                <td>{{ reserve.use_startDate|date:"Y / m / d" }}</td>
                <td>{{ reserve.facility.type }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}

    </table>
    </div>

    <button type="button" class="btn" onclick="window.location.href='{% url 'site:resident:reserve' %}' ">اضافه کردن
        درخواست رزرو جدید
    </button>

    <a href="javascript:void(0)" onclick="printDiv('printableArea')" class="btn"><img
            src="../../static/images/printer.png" title="چاپ" class="linkImg1"></a>
    <a href="javascript:void(0)" onclick="save('reservesCheck.html', 'printableArea')" class="btn"><img
            src="../../static/images/save.png" title="ذخیره" class="linkImg2"></a>
</div>

{% endblock %}

Resident/templates/resident/reserve.html
{% extends 'resident/residentBase.html' %}

{% block title %}ثبت درخواست{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../../static/css/addReqStyle.css"/>{% endblock %}

{% block script %}
function f(){alert("درخواست رزرو با موفقیت ثیت گردید")}
{% endblock %}

{% block content %}

<div class="main">
    <h5>رزرو امکانات</h5>
    <form action="" method="post">
        {% csrf_token %}
        <table class="tbl" border="0" align="center">
            <tbody>

            <tr>

                <td><select id="facility" required name="facility" style="width:150px;">
                   <option disabled selected style="color: black;">---------</option>
                   {% for facility in facilities %}
                       <option value="{{ facility.id }}">{{ facility.type }}
                       </option>
                   {% endfor %}
                    </select></td>
                <td><label for="facility">امکان</label></td>
            </tr>

            <tr>

                <td><input type="date" name="use_startDate_0" id="id_use_startDate_0" style="width:200px;">
                    <input type="time" name="use_startDate_1" id="id_use_startDate_1" style="width:150px;">
                </td>
                <td><label for="time">زمان و تاریخ شروع استفاده</label></td>
            </tr>

            <tr>

                <td>
                    <input type="date" name="use_finishDate_0" id="id_use_finishDate_0" style="width:200px;">
                    <input type="time" name="use_finishDate_1" id="id_use_finishDate_1" style="width:150px;">
{#                    <input class="dur" type="number" name="duration_minute" id="duration_minute">#}
{#                    <span class="semicolon">:</span>#}
{#                    <input class="dur" type="number" name="duration_time" id="duration_time">#}
                </td>

                <td><label for="dur">زمان و تاریخ پایان استفاده</label></td>
            </tr>


            </tbody>
        </table>
    <button type="submit" class="btn" onclick="f()">ثبت</button>
    </form>



</div>

{% endblock %}

Resident/templates/resident/residentBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
     <style>
        @font-face {
             font-family: 'brandon';
             src: url("{% static "fonts/BRoya.ttf"%}") format('truetype');
             font-style: normal;
             font-weight: normal;
         }
         body{
             margin: 0;
         }
        .container{
            margin: 0;
            padding:0;
            width:100%;
        }
        #footer {
            font-family: brandon;
            text-align: center;
            width: 100%;
            position: absolute;
            height: 150px;
            background-color: #00293E;
            color: white;
            margin-top: 50px;

        }

        .foot{
           font-size: 16px;
        }
         .text-danger{
             color: red;
             direction: rtl;

         }

         input, select {
             width: 250px;
             height: 35px;
             border-radius: 3px;
             font-family: brandon;
             font-size: 18px;
             text-align: right;
         }

        #id_text {
            font-family: brandon;
            font-size: 18px;
            text-align: right;
            width: 400px;
            height: 150px;
         }

         .address{
         width: 250px;
         position: absolute;
         top: 6%;
         right: 2%;
         font-size: 18px;
         font-family: brandon;
         color: white;
         text-align: right;
         }

         .logo{
         position: absolute;
         top: 20%;
         left: 5%;
         max-width: 100px;
         }

         .highlighted {
    background-color: rgba(0,0,0,.4);
    text-align: center;
}


    </style>
    {% block css %}{% endblock %}
    <script>{% block script %}{% endblock %}</script>
</head>
<body>
    <div class="container">

    <img class="cover" src="../../../static/images/test.jpg">
    <div class="topright"><img class="img-circle" src="../../../static/images/user_profile_female.jpg">
        <p class="highlighted"> {{ user.get_full_name }}</p></div>
    <div class="topleft" style="display:grid; z-index:5">
        <a href="{% url 'site:resident:select_contact' %}"><img src="../../../static/images/message.png"
                                                                style="height:50px;width:50px;"/></a>
        <a href="/logout/">خروج</a>
        <p>96/5/5</p>

    </div>

</div>
    <div class="menu">
        <ul>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">ویرایش اطلاعات</a>
                <div class="dropdown-content">
                    <a href="{% url 'site:resident:edit_profile'%}">اطلاعات حساب</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">بورد</a>
                <div class="dropdown-content">
                    <a href="{% url 'site:resident:board' %}">اخبار</a>
                    <a href="{% url 'site:resident:events' %}">رویدادها</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">گزارشات</a>
                <div class="dropdown-content">
                    <a href="{% url 'site:resident:payingReports_user'%}">پرداخت ها</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">رزرو</a>
                <div class="dropdown-content">
                    <a href="{% url 'site:resident:reserve'%}">ثبت رزرو</a>
                    <a href="{% url 'site:resident:myReserves'%}">وضعیت رزرو ها</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">امور مالی</a>
                <div class="dropdown-content">
                    <a href="{% url 'site:resident:increase'%}">افزایش اعتبار</a>
                    <a href="{% url 'site:resident:bills'%}">پرداخت شارژ</a>
                </div>
            </li>

        </ul>
    </div>

{% block content %}
{% endblock %}

<div id="footer">
    <div class="address">
        <p>نشانی: تهران، خیابان آزادی، دانشگاه شریف، دانشکده مهندسی کامپیوتر</p>
        <p>تلفن تماس: 02166161234</p>
    </div>

    <p class="footer-block">طراحی و اجرا: شرکت نرم افزاری آسا</p>
    <p class="foot">کلیه حقوق محفوظ و متعلق به آسا می باشد</p>
    <div ><img class="logo" src="../../../static/images/LOGO.png"></div>
</div>
</body>

</body>
</html>

Resident/templates/resident/viewBill.html
{% extends 'resident/residentBase.html' %}

{% block title %}مشاهده قبض{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
    function f(){alert("درخواست رزرو با موفقیت تایید گردید")}
    function g(){alert("درخواست رزرو با موفقیت رد گردید")}
    function printDiv(divName) {
    var printContents = document.getElementById(divName).innerHTML;
    var originalContents = document.body.innerHTML;

    document.body.innerHTML = printContents;

    window.print();

    document.body.innerHTML = originalContents;
    }
    function save(filename, divName) {
    var el = document.createElement('a');
    el.setAttribute('href', 'data:text/html;charset=utf-8,' +
    encodeURIComponent(document.getElementById(divName).innerHTML));
    el.setAttribute('download', filename);
    el.style.display = 'none';
    document.body.appendChild(el);
    el.click();
    document.body.removeChild(el);
    }
{% endblock %}

{% block content %}

<div class="main">
    <h5>قبض شماره {{ receipt.id }}</h5>

    <div id="printableArea">
        <table>

            <tr>
            <th>مبلغ شما = (مبلغ
                * {{ receipt.resident.member_count }}) / {{ size }}</th>
            <th>مبلغ</th>
            <th>زمان و تاریخ</th>
            <th>توضیحات</th>
            <th>نوع</th>

        </tr>
        {% for event, eventCost in events %}
            <tr>
                <td>{{ eventCost }}</td>
                <td>{{ event.cost }}</td>
                <td>{{ event.date|date:"Y / m / d" }}</td>
                <td>{{ event.description }}</td>
                <td>رویداد</td>

            </tr>
        {% endfor %}
        {% for bill, billCost in bills %}
            <tr>
                <td>{{ billCost }}</td>
                <td>{{ bill.cost }}</td>
                <td>{{ bill.date|date:"Y / m / d" }}</td>
                <td>{{ bill.get_type_display }}</td>
                <td>قبض</td>

            </tr>
        {% endfor %}
        {% for reserve in reserves %}
            <tr>
                <td>{{ reserve.cost }}</td>
                <td>{{ reserve.cost }}</td>
                <td>{{ reserve.reserve_date|date:"Y / m / d" }}</td>
                <td>{{ reserve.facility.type }}</td>
                <td>رزرو</td>

            </tr>
        {% endfor %}
        <tr>
            <td>{{ receipt.cost }}</td>
            <td>مجموع</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>


    </table>
    </div>

    <button type="button" class="btn"
            onclick="window.location.href='{% url 'site:resident:select_payWay' receipt.id %}' ">
        پرداخت
    </button>
    <br><br><br>
    <a href="javascript:void(0)" onclick="printDiv('printableArea')" class="btn"><img
            src="../../static/images/printer.png" title="چاپ" class="linkImg1"></a>
    <a href="javascript:void(0)" onclick="save('reservesCheck.html', 'printableArea')" class="btn"><img
            src="../../static/images/save.png" title="ذخیره" class="linkImg2"></a>

</div>

{% endblock %}