BuildingManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('MySite.urls', namespace="site")),
    url(r'^admin/', admin.site.urls),
]

Manager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^view_bills/$', views.view_bills, name='viewBills'),
    url(r'^calculate_receipts/$', views.calculate_receipts, name='calculateReceipts'),
    url(r'^(?P<reserve_id>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.[0-9]*\W\d{2}:\d{2})/reject_reserve/$',
        views.reject_reserve,
        name='reject_reserve'),
    url(r'^(?P<reserve_id>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.[0-9]*\W\d{2}:\d{2})/accept_reserve/$',
        views.accept_reserve, name='accept_reserve'),
    url(r'^(?P<request_id>[0-9]+)/view_request/$', views.view_request, name='viewRequest'),
    url(r'^(?P<request_id>[0-9]+)/delete_request/$', views.delete_request, name='delete_request'),
    url(r'^select_contact/$', views.select_contact, name='select_contact'),
    url(r'^message/$', views.message, name='message'),
    url(r'^(?P<neighbour_id>[0-9]+)/edit_n/$', views.edit_n, name='editN'),
    url(r'^add_unit/$', views.add_unit, name='addUnit'),
    url(r'^add_request/$', views.add_request, name='addRequest'),
    url(r'^add_neighbour/$', views.add_neighbour, name='addNeighbour'),
    url(r'^requests/$', views.requests, name='requests'),
    url(r'^reserves_check/$', views.reserves_check, name='reservesCheck'),
    url(r'^paying_reports/$', views.paying_reports, name='payingReports'),
    url(r'^edit_unit/$', views.edit_unit, name='editUnit'),
    url(r'^edit_neighbours/$', views.edit_neighbours, name='editNeighbours'),
    url(r'^edit_complex_information/$', views.edit_complex_information, name='edit_complex_information'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^board/add_to_board$', views.add_to_board, name='add_to_board'),
    url(r'^board/$', views.view_board, name='board'),
    url(r'^events/$', views.view_event, name='events'),
    url(r'^enterBill/$', views.enter_bill, name='enterBill'),
    url(r'^(?P<unit_id>[0-9]+)/delete_unit/$', views.delete_unit, name='deleteUnit'),
    url(r'^(?P<neighbour_id>[0-9]+)/delete_neighbour/$', views.delete_neighbour, name='deleteNeighbour'),
    url(r'^$', views.account, name='account'),
    url(r'^add_facility/$', views.add_facility, name='addFacility'),
    url(r'^edit_facility/$', views.edit_facility, name='editFacility'),
    url(r'^(?P<facility_id>[0-9]+)/delete_facility/$', views.delete_facility, name='deleteFacility'),
    ]

MySite/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^resident/', include('Resident.urls', namespace="resident")),
    url(r'^manager/', include('Manager.urls', namespace="manager")),
    url(r'^$', views.index, name='index'),
    url(r'^send_feedback/$', views.send_feedback,name='send_feedback'),
    url(r'^logout/$', views.logout, name='log_out'),
    url(r'^forget_password/$', views.forget_password, name='forget_password'),
]

Manager/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models

from MyUser.models import Member

SUBJECT_CHOICES = (
    ('E', 'خطا در سامانه'),
    ('S', 'پیشنهاد امکانات جدید یا تغییر'),
    ('Q', 'سوال و راهنمایی'),
    ('C', 'شکایات'),
    ('O','سایر')
)

STATE_CHOICES = (
    ('W', 'در صف انتظار'),
    ('C', 'بررسی شده')
)


class Manager(models.Model):
    member = models.OneToOneField(Member)
    bank_account_num = models.IntegerField()

    def __str__(self):
        return str(self.member)

    # don't forget to write save


class Request(models.Model):
    manager = models.ForeignKey(Manager)
    title = models.CharField(max_length=20)
    subject = models.CharField(max_length= 1, choices=SUBJECT_CHOICES)
    text = models.TextField()
    state = models.CharField(max_length=2, choices=STATE_CHOICES)

MySite/models.py
# Create your models here.

from django.db import models

from Manager.models import Manager

FACILITY_TYPE = (
    ('P', 'استخر'),
    ('A', 'آمفی تئاتر'),
    ('G', 'سالن ورزش'),
    ('B', 'آلاچیق')
)

BILL_TYPE = (
    ('W', 'آب'),
    ('E', 'برق'),
    ('G', 'گاز'),
    ('P', 'تلفن')
)


class Unit(models.Model):
    area = models.IntegerField()
    block = models.ForeignKey('Block')

    def __str__(self):
        return str(self.block) + 'Unit : ' + str(self.id)


class Block(models.Model):
    complex = models.ForeignKey('Complex')

    def __str__(self):
        return 'complex: ' + str(self.complex.name) + ' block: ' + str(self.id)


class Bill(models.Model):
    type = models.CharField(max_length=1, choices=BILL_TYPE)
    num = models.IntegerField()
    cost = models.IntegerField()
    date = models.DateField()
    block = models.ForeignKey(Block)

    def str(self):
        return 'block' + str(self.block) + ' num: ' + str(self.num)


class Complex(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    manager = models.OneToOneField(Manager)
    unit_number = models.IntegerField()
    last_calculation_date = models.DateField()

    def __str__(self):
        return 'name: ' + self.name + ' manager: ' + str(self.manager)


class Facility(models.Model):
    type = models.CharField(max_length=20)
    block = models.ForeignKey('Block')
    cost = models.IntegerField()

    def __str__(self):
        return self.type


class Board(models.Model):
    block = models.OneToOneField(Block)

    def __str__(self):
        return str(self.block) + ' board: ' + str(self.id)


class News(models.Model):
    board = models.ForeignKey(Board)
    date = models.DateField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.board) + ' title: ' + str(self.title)


class Event(models.Model):
    board = models.ForeignKey(Board)
    date = models.DateField()
    cost = models.IntegerField()
    description = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.board) + ' description: ' + self.description

MyUser/models.py
from django.contrib.auth.models import User
from django.db import models


MESSAGE_THEME_TYPE = (
    (0, 'بدون قالب'),
    (1, 'قالب 1'),
    (2, 'قالب 2'),
)


class Member(models.Model):
    user = models.OneToOneField(User)
    phone_number = models.CharField(max_length=12)
    image = models.FileField(upload_to='static/images/profile_picture',
                             default='../static/images/user_profile_female.jpg')

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Message(models.Model):
    text = models.TextField(max_length=1000)
    theme_type = models.IntegerField(choices=MESSAGE_THEME_TYPE)
    sender = models.ForeignKey(Member, related_name='sender')
    receiver = models.ForeignKey(Member, related_name='receiver')

    def __str__(self):
        return 'sender: ' + str(self.sender) + ' receiver: ' + str(self.receiver)

Resident/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from MySite.models import Facility, Unit
from MyUser.models import Member

RESERVE_STATE = {
    ('NC', 'بررسی نشده'),
    ('R', 'رد شده'),
    ('A', 'تایید شده')
}

RECEIPT_STATE = {
    ('P', 'پرداخت شده'),
    ('NP', 'پرداخت نشده')
}


class Resident(models.Model):
    member = models.OneToOneField(Member)
    member_count = models.IntegerField()
    car_count = models.IntegerField()
    unit = models.OneToOneField(Unit)

    def __str__(self):
        return str(self.member)


class Reserve(models.Model):
    reserve_date = models.DateTimeField(primary_key=True)
    use_finishDate = models.DateTimeField()
    use_startDate = models.DateTimeField()
    cost = models.IntegerField()
    state = models.CharField(max_length=2, choices=RESERVE_STATE)
    resident = models.ForeignKey(Resident)
    facility = models.ForeignKey(Facility)

    def __str__(self):
        return 'resident: ' + str(self.resident) + ' facility: ' + str(self.facility) + ' reserve date:' + \
               str(self.reserve_date)


class Receipt(models.Model):
    start_date = models.DateField()
    finish_date = models.DateField()
    cost = models.IntegerField(null=True)
    state = models.CharField(max_length=2, choices=RECEIPT_STATE)
    resident = models.ForeignKey(Resident)

    def __str__(self):
        return 'date: ' + str(self.start_date) + ' cost: ' + str(self.cost)


class Account(models.Model):
    cash = models.PositiveIntegerField()
    resident = models.OneToOneField(Resident)

    def __str__(self):
        return 'resident: ' + str(self.resident)


class PayByBank(models.Model):
    date = models.DateField(primary_key=True)
    amount = models.IntegerField()
    resident = models.OneToOneField(Resident)
    receipt = models.OneToOneField(Receipt)

    def __str__(self):
        return 'resident: ' + str(self.resident) + ' date: ' + str(self.date)


class PayByAccount(models.Model):
    date = models.DateField(primary_key=True)
    amount = models.IntegerField()
    account = models.OneToOneField(Account)
    receipt = models.OneToOneField(Receipt)

    def __str__(self):
        return str(self.account) + ' date: ' + str(self.date)

Manager/forms.py
import django
from django.forms import TextInput

from Manager.models import Manager, Request
from MyUser.models import Message
from MySite.models import Bill


class ManagerForm(django.forms.ModelForm):
    class Meta:
        model = Manager
        fields = '__all__'


class RequestForm(django.forms.ModelForm):
    class Meta:
        model = Request
        exclude = ['manager', 'state']


class MessageForm(django.forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['sender', 'theme_type']


class BillForm(django.forms.ModelForm):
    class Meta:
        model = Bill
        exclude = ['date']

Manager/templates/account.html
{% extends 'managerBase.html' %}

{% block title %}حساب کاربری - مدیر{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/addReqStyle.css"/>{% endblock %}

{% block script %}
    function f(){alert("همسایه با موفقیت اضافه شد"); window.location.href="editNeighbours.html";}
{% endblock %}

{% block content %}
{% endblock %}

Manager/templates/addNeighbour.html
{% extends 'managerBase.html' %}

{% block title %}اضافه کردن همسایه{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/addReqStyle.css"/>{% endblock %}

{% block script %}
    function f(){alert("همسایه با موفقیت اضافه شد"); window.location.href="editNeighbours.html";}
{% endblock %}

{% block content %}

<div class="main">
    <h5>وارد کردن اطلاعات همسایه ی جدید</h5>
    <form action="" method="post">
        <table class="tbl" border="0" align="center">
            <tbody>

            <tr>

               <td><input type="number" name="unit" id="unit" min="1" max="100"></td>
                <td><label for="unit">شماره واحد </label></td>
            </tr>

            <tr>

                <td><input type="text" name="username" id="username"></td>
                <td><label for="username"> نام کاربری سرپرست</label></td>
            </tr>

            <tr>

               <td><input type="number" name="count" id="count" min="1" max="10"></td>
                <td><label for="count">تعداد اعضای خانواده </label></td>
            </tr>

            <tr>

               <td><input type="number" name="car" id="car" min="1" max="5"></td>
                <td><label for="car">تعداد اتومبیل </label></td>
            </tr>


            </tbody>
        </table>
    </form>

    <button type="button" class="btn" onclick="f()">ثبت</button>

</div>

{% endblock %}

Manager/templates/addUnit.html
{% extends 'managerBase.html' %}

{% block title %}اضافه کردن واحد{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/addReqStyle.css"/>{% endblock %}

{% block script %}
    function f(){alert("واحد با موفقیت اضافه شد"); window.location.href="editUnit.html";}
{% endblock %}

{% block content %}
<div class="main">
    <h5>وارد کردن اطلاعات واحد جدید</h5>
    <form action="Welcome.html" method="post">
        <table class="tbl" border="0" align="center">
            <tbody>

            <tr>

               <td><input type="number" name="unit" id="unit" min="1" max="100"></td>
                <td><label for="unit">شماره واحد </label></td>
            </tr>

            <tr>

               <td><input type="number" name="block" id="block" min="1" max="100"></td>
                <td><label for="block">شماره بلوک </label></td>
            </tr>

            <tr>

               <td><input type="number" name="area" id="area" min="1" max="500"></td>
                <td><label for="area">متراژ</label></td>
            </tr>


            </tbody>
        </table>
    </form>

    <button type="button" class="btn" onclick="f()">ثبت</button>

</div>
{% endblock %}

Manager/templates/add_to_board.html
{% extends 'managerBase.html' %}

{% block title %}اضافه کردن به بورد{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
    function f(){alert("درخواست با موفقیت ثبت شد."); window.location.href="editNeighbours.html";}
    function g(){
       var e = document.getElementById("from");
       var strUser = e.options[e.selectedIndex].value;
       var f = document.getElementById("cost_tag");
       if (strUser == "event")
          f.style.display='block';
       else
          f.style.display='none';
    }
{% endblock %}

{% block content %}
<div class="main">
    <h5>افزودن رویداد/خبر به برد</h5>
    <form action="" method="post">
        {% csrf_token %}
        <table class="tbl" border="0" align="center">
            <tbody>

            <tr>

               <td>
         <select class="from" name="choose"  id ="from" placeholder="" onchange="g()">
                    <option value="event">رویداد</option>
                    <option value="news">خبر</option>
                </select>
        </td>
                <td><label for="unit">نوع </label></td>
            </tr>
            <tr>

                <td><input type="text" name="board" id="id_board"></td>
                <td><label for="id_board">شماره بلوک</label></td>
            </tr>

            <tr>

                <td><input type="text" name="title" id="id_title"></td>
                <td><label for="id_title"> عنوان</label></td>
            </tr>

            <tr>

               <td><input type="text" name="description" id="id_description"></td>
                <td><label for="id_description">توضیحات </label></td>
            </tr>

            <tr id="cost_tag"  >

               <td><input type="text" name="cost" id="id_cost"></td>
                <td><label for="id_cost">مبلغ </label></td>
            </tr>


            </tbody>
        </table>
        <input type="submit" class="btn"  value="ثبت">
    </form>

</div>
{% endblock %}

Manager/templates/board.html
{% extends 'managerBase.html' %}

{% block title %}بورد{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}

{% endblock %}

{% block content %}
<div class="main">
    <h5>بورد</h5>


<form action="" method="post">
    {% csrf_token %}
    <select class="from" name="choose"  placeholder="به ترتیب">
        <option value="قدیمی ترین">قدیمی ترین</option>
        <option value="جدیدترین">جدیدترین</option>
    </select>
    <label for="id_startDate">از تاریخ</label>
    <input type="date" name="startDate" id="id_startDate" class="from">
    <label for="id_finishDate">تا تاریخ</label>
    <input type="date" name="finishDate" id="id_finishDate" class="from">
    <input type="submit" class="btn"  value="نمایش">
</form>



    <table>
        <tr>
            <th>توضیحات</th>
            <th>عنوان</th>
            <th>زمان و تاریخ</th>
            <th>شماره بلوک</th>
            <th>شماره</th>
            <th>ردیف</th>
        </tr>
        {% for news in newsSet %}
            <tr>
                <td>{{ news.description }}</td>
                <td>{{ news.title }}</td>
                <td>{{ news.date|date:"Y / m / d" }}</td>
                <td>{{ news.board_id }}</td>
                <td>{{ news.id }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}


    </table>
    <table>
        <tr>
            <th>مبلغ</th>
            <th>توضیحات</th>
            <th>زمان و تاریخ</th>
            <th>شماره بلوک</th>
            <th>شماره</th>
            <th>ردیف</th>
        </tr>
        {% for event in events %}
            <tr>
                <td>{{ event.cost }}</td>
                <td>{{ event.description }}</td>
                <td>{{ event.date|date:"Y / m / d" }}</td>
                <td>{{ event.board_id }}</td>
                <td>{{ event.id }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}


    </table>
    <button type="button" class="btn" onclick="window.location.href='{% url 'site:manager:add_to_board'%}'">افزودن به برد</button>
    <br><br><br>
    <a href="javascript:void(0)" class="btn"><img src="../../static/images/printer.png" class="linkImg1"></a>
    <a href="javascript:void(0)" class="btn"><img src="../../static/images/save.png" class="linkImg2"></a>

</div>
{% endblock %}

Manager/templates/editN.html
{% extends 'managerBase.html' %}

{% block title %}ویرایش کردن همسایه{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/addReqStyle.css"/>{% endblock %}

{% block script %}
    function f(){alert("اطلاعات همسایه با موفقیت به روز شد"); window.location.href="editNeighbours.html";}
{% endblock %}

{% block content %}
<div class="main">
    <h5>ویرایش کردن اطلاعات همسایه</h5>
    <form action="Welcome.html" method="post">
        <table class="tbl" border="0" align="center">
            <tbody>

            <tr>

               <td><input type="number" name="unit" id="unit" min="1" max="100" value="1"></td>
                <td><label for="unit">شماره واحد </label></td>
            </tr>

            <tr>

                <td><input type="text" name="username" id="username" value="hashem.b"></td>
                <td><label for="username"> نام کاربری سرپرست</label></td>
            </tr>

            <tr>

               <td><input type="number" name="count" id="count" min="1" max="10" value="5"></td>
                <td><label for="count">تعداد اعضای خانواده </label></td>
            </tr>

            <tr>

               <td><input type="number" name="car" id="car" min="1" max="5" value="2"></td>
                <td><label for="car">تعداد اتومبیل </label></td>
            </tr>


            </tbody>
        </table>
    </form>

    <button type="button" class="btn" onclick="f()">ثبت</button>

</div>
{% endblock %}

Manager/templates/edit_profile.html
{% extends 'managerBase.html' %}

{% block title %}حساب کاربری - مدیر{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
<div class="main">
    <h5> ویرایش اطلاعات مدیر</h5>
   <form action="" method="post">{% csrf_token %}
        <table class="tbl" border="0" align="center">
            <tbody>

			<tr>
               <td>
                   <input class="{% if form.firstn_ame.errors %}has-error{% endif %}" type="text" name="first_name" id="first_name" value="{{ user.firstname }} ">
                {% if form.first_name.errors %}
        <span class="text-danger" style="text-align:center;">
        {% for error in form.first_name.errors %}{{ error }}{% endfor %}
    </span>
               {% endif %}
               </td>
                <td><label for="first_name">نام حقوقی </label></td>
            </tr>
			<tr>
               <td><input type="text"class=" {% if form.last_name.errors %}has-error{% endif %}" name="last_name" id="last_name"  value="{{ user.lastname }}">
               {% if form.last_name.errors  %}
        <span class="text-danger" style="text-align:center;">
        {% for error in form.last_name.errors %}{{ error }}{% endfor %}
    </span>
    {% endif %}
               </td>
                <td><label for="last_name">نام خانوادگی </label></td>
            </tr>
			<tr>
               <td><input type="text" name="email" id="email" value="{{user.email }}" >
               {% if form.email.errors%}
        <span class="text-danger" style="text-align:center;">
        {% for error in form.email.errors %}{{ error }}{% endfor %}
    </span>
    {% endif %}
               </td>
                <td><label for="email">ایمیل </label></td>
            </tr>
			<tr>
               <td><input type="text" name="username" id="username" value="{{ user.username}} ">
                   {% if form.username.errors %}
        <span class="text-danger" style="text-align:center;">
        {% for error in form.username.errors %}{{ error }}{% endfor %}
    </span>
    {% endif %}
               </td>
                <td><label for="username">نام کاربری </label></td>
            </tr>
            <tr>
               <td><input type="password" name="password1" id="password" class=" {% if form.password2.errors %}has-error{% endif %}">
                {% if form.password2.errors %}
        <span class="text-danger">
        <p>{% for error in form.password2.errors %}{{ error }}{% endfor %}</p>
    </span>
    {% endif %}
               </td>
                <td><label for="password">رمز </label></td>
            </tr>
			<tr>
               <td><input type="password" name="password2" id="passworda " class=" {% if form.password2.errors %}has-error{% endif %}">
                {% if form.password2.errors %}
        <span class="text-danger">
        <p>{% for error in form.password2.errors %}{{ error }}{% endfor %}</p>
    </span>
    {% endif %}
               </td>
                <td><label for="passworda">تایید رمز </label></td>
            </tr>
            <tr>
               <td><input type="text" name="phone_number" id="phoneNumber" value="{{user.member.phone_number}} "></td>
                <td><label for="phoneNumber">شماره تلفن </label></td>
            </tr>
            {% if user.mamber_set.manager_set %}
                <tr>
               <td><input type="text" name="bank_acunt" id="bankAccount" value="{{user.member_set.manager_set.bank_acunt_num}} "></td>
                <td><label for="bankAccount">حساب بانکی </label></td>
            </tr>
            {% endif %}
            {% if form.errors %}
                <div class="text-danger"> {{ form.errors.value }} </div>
        {% endif %}
            </tbody>
        </table>
<input type="submit" name="submit"  tabindex="4"
                           class="form-control btn btn-login" value="ویرایش" placeholder="ویرایش">


    </form>

    <!--button type="button" class="btn" onclick="f()">ثبت</button-->
</div>
{% endblock %}

Manager/templates/payingReports.html
{% extends 'managerBase.html' %}

{% block title %}گزارشات پرداخت ها{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
    function f(){alert("درخواست رزرو با موفقیت تایید گردید")}
{% endblock %}

{% block content %}

<div class="main">
    <h5>پرداخت ها</h5>

<form action="" method="post">
    {% csrf_token %}
    <label for="id_unit">شماره واحد</label>
    <input type="number" name="unit" id="id_unit" class="from">
    <select class="from" name="choose"  placeholder="به ترتیب">
        <option value="قدیمی ترین">قدیمی ترین</option>
        <option value="جدیدترین">جدیدترین</option>
    </select>
    <label for="id_startDate">از تاریخ</label>
    <input type="date" name="startDate" id="id_startDate" class="from">
    <label for="id_finishDate">تا تاریخ</label>
    <input type="date" name="finishDate" id="id_finishDate" class="from">
    <input type="submit" class="btn"  value="نمایش">
</form>

    <table>
        <tr>
            <th>مبلغ</th>
            <th>زمان و تاریخ پرداخت</th>
            <th>شماره قبض</th>
            <th>شماره واحد</th>
            <th>شماره بلوک</th>
            <th>شماره</th>
        </tr>
        {% for report in bank_reports %}
            <tr>
                <td>{{ report.amount }}</td>
                <td>{{ report.date|date:"Y / m / d" }}</td>
                <td>{{ report.receipt_id }}</td>
                <td>{{ report.resident.unit_id }}</td>
                <td>{{ report.resident.unit.block_id }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}

        {% for report in account_reports %}
            <tr>
                <td>{{ report.amount }}</td>
                <td>{{ report.date|date:"Y / m / d" }}</td>
                <td>{{ report.receipt_id }}</td>
                <td>{{ report.account.resident.unit_id }}</td>
                <td>{{ report.account.resident.unit.block_id }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}

    </table>

    <a href="javascript:void(0)" class="btn"><img src="../../static/images/printer.png" title="چاپ" class="linkImg1"></a>
    <a href="javascript:void(0)" class="btn"><img src="../../static/images/save.png" title="ذخیره" class="linkImg2"></a>

</div>

{% endblock %}

Manager/templates/reservesCheck.html
{% extends 'managerBase.html' %}

{% block title %}درخواست های رزرو{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="../../static/css/viewBillStyles.css"/>{% endblock %}

{% block script %}
    function f(){alert("درخواست رزرو با موفقیت تایید گردید")}
{% endblock %}

{% block content %}
<div class="main">
    <h5>درخواست های رزرو</h5>

<form action="" method="post">
    {% csrf_token %}
    <select class="from" name="choose"  placeholder="به ترتیب">
        <option value="قدیمی ترین">قدیمی ترین</option>
        <option value="جدیدترین">جدیدترین</option>
    </select>
    <label for="id_startDate">از تاریخ</label>
    <input type="date" name="startDate" id="id_startDate" class="from">
    <label for="id_finishDate">تا تاریخ</label>
    <input type="date" name="finishDate" id="id_finishDate" class="from">
    <input type="submit" class="btn"  value="نمایش">
</form>


    <table>
        <tr>
            <th style="width: 5%"> </th>
            <th style="width: 10%">مبلغ به ریال </th>
            <th style="width: 10%">وضعیت</th>
            <th style="width: 5%">مدت</th>
            <th style="width: 15%">زمان و تاریخ ایجاد</th>
            <th style="width: 15%">زمان و تاریخ استفاده</th>
            <th style="width: 10%">امکان</th>
            <th style="width: 10%">شماره واحد</th>
            <th style="width: 10%">شماره بلوک</th>
            <th style="width: 10%">ردیف</th>
        </tr>


        {% for reserve in reserves %}
            <tr>
                <td><a href="{% url 'site:manager:accept_reserve' reserve.reserve_date %}" onclick="f()">تایید</a></td>
                <td>{{ reserve.cost }}</td>
                <td>{{ reserve.get_state_display }}</td>
                <td>{{ reserve.duration }}</td>
                <td>{{ reserve.reserve_date|date:"Y / m / d" }}</td>
                <td>{{ reserve.use_date|date:"Y / m / d" }}</td>
                <td>{{ reserve.facility.get_type_display }}</td>
                <td>{{ reserve.resident.unit.block_id }}</td>
                <td>{{ reserve.resident.unit_id }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}

    </table>

    <a href="javascript:void(0)" class="btn"><img src="../../static/images/printer.png" title="چاپ" class="linkImg1"></a>
    <a href="javascript:void(0)" class="btn"><img src="../../static/images/save.png" title="ذخیره" class="linkImg2"></a>

</div>
{% endblock %}